service: mpp-client-sqs-adapter

# Create an optimized package for our functions
package:
  individually: true

custom:
  stage: ${opt:stage, self:provider.stage}
  bundle:
    sourcemaps: true      # Enable source maps
    caching: true         # Enable Webpack caching
    stats: false          # Don't print out any Webpack output
    linting: false         # Enable linting as a part of the build process

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1
  account: 193400596843
  environment: ${file(env.yml):${self:custom.stage}}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:PutParameter
        - ssm:GetParameters
        - ssm:GetParametersByPath
        - ssm:GetParameterHistory
      Resource:
        - "arn:aws:ssm:${self:provider.region}:${self:provider.account}:parameter/mpp-clients/*"
    - Effect: "Allow"
      Action:
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:GetQueueAttributes
        - sqs:ReceiveMessage
      Resource: "arn:aws:sqs:${self:provider.region}:*:JobsQueue"
    - Effect: "Allow"
      Action:
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
        - sqs:SendMessage  
        - sqs:GetQueueAttributes
      Resource: "arn:aws:sqs:${self:provider.region}:*:DeadLetterQueue"

functions:
  SPRunner:
    handler: handlers/sp-runner-handler.main
  JobsDispatcher:
    handler: handlers/jobs-dispatcher-handler.main

resources:
  Resources:
    JobsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "JobsQueue"
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - JobsDeadLetterQueue
              - Arn
          maxReceiveCount: 4
    JobsDeadLetterQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "JobsDeadLetterQueue"
    JobsQueueUrlParameter:
      Type: "AWS::SSM::Parameter"
      Properties:
        Name: "/mpp-clients/JOBS_QUEUE_URL"
        Value:
          Ref: JobsQueue
        Type: String
