service: mpp-client-sqs-adapter

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-pseudo-parameters

custom:
  stage: ${opt:stage, self:provider.stage}
  pseudoParameters:
    allowReferences: false
  ssmParamNamespace: /mpp-client-sqs-adapter/${self:custom.stage}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-northeast-1
  environment: ${file(env.yml):${self:custom.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ssm:GetParameter
        - ssm:PutParameter
        - ssm:GetParameters
        - ssm:GetParametersByPath
        - ssm:GetParameterHistory
      Resource:
        - "arn:aws:ssm:#{AWS::Region}:#{AWS::AccountId}:parameter/mpp-clients/*"
    - Effect: "Allow"
      Action:
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:GetQueueAttributes
        - sqs:ReceiveMessage
      Resource: "arn:aws:sqs:${self:provider.region}:*:JobsQueue"
    - Effect: "Allow"
      Action:
        - sqs:DeleteMessage
        - sqs:GetQueueUrl
        - sqs:SendMessage
        - sqs:GetQueueAttributes
      Resource: "arn:aws:sqs:${self:provider.region}:*:DeadLetterQueue"
    - Effect: "Allow"
      Action:
        - lambda:InvokeAsync
        - lambda:InvokeFunction
      Resource: "*"

functions:
  SPRunner:
    handler: handlers/sp-runner-handler.main
    timeout: 60
  JobsDispatcher:
    handler: handlers/jobs-dispatcher-handler.main
    timeout: 60

resources:
  - ${file(resources/queue-topic.yml)}
